{% set name = "starlite-jwt" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starlite-jwt-{{ version }}.tar.gz
  sha256: be7bdac22300308b437a9e10f685d08aaeb98eea0cc5c32167a6517e4a3f580b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - python >=3.7,<4.0
    - cryptography
    - python-jose
    - starlite >=1.16.0

test:
  imports:
    - starlite_jwt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/starlite-api/jwt-auth
  dev_url: https://starlite-api.github.io/starlite-jwt/
  summary: A JWT auth toolkit for Starlite
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
