{% set name = "starlite-jwt" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 53b8bf35db63249dcc26275412f8aa5deb43365a14a7e1a31cc15b2e951cacdf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - python >=3.7,<4.0
    - cryptography
    - python-jose
    - starlite >=1.24.0

test:
  imports:
    - starlite_jwt
  commands:
    - pip check
  requires:
    - picologging
    - pip

about:
  home: https://starlite-api.github.io/starlite-jwt/
  dev_url: https://github.com/starlite-api/jwt-auth
  summary: A JWT auth toolkit for Starlite
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
