{% set name = "starlite-jwt" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starlite-jwt-{{ version }}.tar.gz
  sha256: 3756c194d98bd19bf1f7d9fa050b8046b0e6338a1d8fc6e075f60b5a30475925

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - python >=3.7,<4.0
    - cryptography
    - python-jose
    - starlite >=1.24.0

test:
  imports:
    - starlite_jwt
  commands:
    - pip check
  requires:
    - picologging
    - pip

about:
  home: https://starlite-api.github.io/starlite-jwt/
  dev_url: https://github.com/starlite-api/jwt-auth
  summary: A JWT auth toolkit for Starlite
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
